// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 7);
user_pref("app.normandy.user_id", "d914572f-e1da-409a-aee8-ea50cd6c3087");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 31);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1575341151);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 87);
user_pref("browser.newtabpage.activity-stream.impressionId", "{e7ac4c0b-4749-4353-91cf-2c85561c5d98}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1575341170933");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1575342978933");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1575341159546");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1575344759546");
user_pref("browser.search.region", "IN");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1575341154");
user_pref("browser.slowStartup.averageTime", 6655);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20191031062442");
user_pref("browser.startup.homepage_override.mstone", "70.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1575341154);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "70.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "af57cddb324549de84c47d5fc5ca6883");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "70.0.1");
user_pref("extensions.lastPlatformVersion", "70.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"be15293c-bd87-40e1-ab7b-44141b11a0b6\",\"screenshots@mozilla.org\":\"569b9a2e-ad6e-4873-b330-c7d3e65be979\",\"webcompat-reporter@mozilla.org\":\"27160dd0-e836-4c58-a5a0-b80362f1fee3\",\"webcompat@mozilla.org\":\"48c2dfb1-c3f9-4413-9a24-287679c097f9\",\"default-theme@mozilla.org\":\"1b0f92b5-fb60-49ed-b8a6-b19775e5ccdb\",\"google@search.mozilla.org\":\"e1f6a590-bb3a-449f-b6e3-c887b06740f5\",\"amazondotcom@search.mozilla.org\":\"b1543669-a85e-4726-a2d6-35819dacf935\",\"bing@search.mozilla.org\":\"794ec830-b83c-4481-a08e-7fd45333ad57\",\"ddg@search.mozilla.org\":\"418f2fda-fdea-4ef8-ade0-7910a3129fc3\",\"ebay@search.mozilla.org\":\"9460b121-abd1-4541-87ab-f74d2b92994b\",\"twitter@search.mozilla.org\":\"301f5f8e-8104-4ffc-8bc7-5d8a15237cc2\",\"wikipedia@search.mozilla.org\":\"95edfb6c-92dd-47b4-87e0-42218285ac97\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "ae77198c-de8c-4212-8d90-04aa750a2bd3");
user_pref("security.sandbox.plugin.tempDirSuffix", "a2b7a659-ca30-4d65-9d49-7ead27e3ce97");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1575341147);
user_pref("toolkit.telemetry.cachedClientID", "38b17c75-8cc3-4b04-9767-224868537e09");
user_pref("toolkit.telemetry.previousBuildID", "20191031062442");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.extendedTriplets.experiment", "control");
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
